package com.esprit.campconnect.Reservation.Enum;

public enum NotificationType {
    BOOKING_CONFIRMED,
    PAYMENT_CONFIRMED,
    WAITLIST_JOINED,
    WAITLIST_PROMOTED,
    WAITLIST_OFFER_EXPIRED,
    REFUND_PROCESSED,
    EVENT_REMINDER,
    EVENT_POSTPONED,
    EVENT_CANCELLED,
    EVENT_STARTED,
    EVENT_COMPLETED,
    ATTENDANCE_RECORDED,
    FEEDBACK_REQUESTED
}
