sonar.projectKey=campconnect-frontend
sonar.projectName=CampConnect Frontend
sonar.projectVersion=0.0.0

sonar.sourceEncoding=UTF-8
sonar.sources=src/app/features/public/events,src/app/features/admin/events,src/app/features/admin/reservations
sonar.exclusions=**/*.spec.ts
sonar.coverage.exclusions=**/*.model.ts,**/*.module.ts,**/*.routes.ts,**/environment*.ts
sonar.tests=src/app/features/public/events,src/app/features/admin/events,src/app/features/admin/reservations
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/campconnect-frontend/lcov.info
sonar.typescript.tsconfigPath=tsconfig.sonar.json
