sonar.projectKey=campconnect-frontend
sonar.projectName=CampConnect Frontend
sonar.projectVersion=0.0.0

sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=dist/**,node_modules/**,coverage/**,src/**/*.spec.ts
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/campconnect-frontend/lcov.info
