package com.esprit.campconnect.Notification.Entity;

public enum NotificationType {
    WELCOME,
    SECURITY,
    PASSWORD_RESET,
    PROFILE_UPDATED,
    GOOGLE_LOGIN,
    ASSURANCE_REMBOURSEMENT,
    ASSURANCE_SOUSCRIPTION_ACCEPTEE,
    ASSURANCE_EXPIRATION,
    ASSURANCE_SINISTRE_EN_COURS
}
